package jsf.entidades;

// Generated 10-jul-2015 18:56:30 by Hibernate Tools 4.3.1

/**
 * EmpDetailsView generated by hbm2java
 */
public class EmpDetailsView implements java.io.Serializable {

	private EmpDetailsViewId id;

	public EmpDetailsView() {
	}

	public EmpDetailsView(EmpDetailsViewId id) {
		this.id = id;
	}

	public EmpDetailsViewId getId() {
		return this.id;
	}

	public void setId(EmpDetailsViewId id) {
		this.id = id;
	}

}
