package jsf.entidades;

// Generated 10-jul-2015 18:56:30 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Regions generated by hbm2java
 */
public class Regions implements java.io.Serializable {

	private int regionId;
	private String regionName;
	private Set<Countries> countrieses = new HashSet<Countries>(0);

	public Regions() {
	}

	public Regions(int regionId) {
		this.regionId = regionId;
	}

	public Regions(int regionId, String regionName, Set<Countries> countrieses) {
		this.regionId = regionId;
		this.regionName = regionName;
		this.countrieses = countrieses;
	}

	public int getRegionId() {
		return this.regionId;
	}

	public void setRegionId(int regionId) {
		this.regionId = regionId;
	}

	public String getRegionName() {
		return this.regionName;
	}

	public void setRegionName(String regionName) {
		this.regionName = regionName;
	}

	public Set<Countries> getCountrieses() {
		return this.countrieses;
	}

	public void setCountrieses(Set<Countries> countrieses) {
		this.countrieses = countrieses;
	}

}
